---
name: Flake Finder

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  e2e:
    name: E2E
    if: github.repository_owner == 'submariner-io'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.10

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.10

      - name: Raise an issue to report flaky test failure
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Flaky Failure make e2e
          content-filepath: .github/ISSUE_TEMPLATE/flaky_failure_automated.md
          labels: automated, flaky failure
